version: 2
jobs:
  publish-latest:
    environment:
      IMAGE_NAME: miketruman/androiddocker
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker images
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t $IMAGE_NAME:71 --build-arg ABIS=google_apis --build-arg ANDROID=android-25 .
            docker push $IMAGE_NAME:71
            docker build -t $IMAGE_NAME:8 --build-arg ABIS=google_apis --build-arg ANDROID=android-26 .
            docker push $IMAGE_NAME:8
            docker build -t $IMAGE_NAME:9 --build-arg ABIS=google_apis --build-arg ANDROID=android-28 .
            docker push $IMAGE_NAME:9
            docker build -t $IMAGE_NAME:9play --build-arg ABIS=google_apis_playstore --build-arg ANDROID=android-28 .
            docker push $IMAGE_NAME:9play
            docker build -t $IMAGE_NAME:10 --build-arg ABIS=google_apis --build-arg ANDROID=android-29 .
            docker push $IMAGE_NAME:10
            docker build -t $IMAGE_NAME:10play --build-arg ABIS=google_apis_playstore --build-arg ANDROID=android-29 .
            docker push $IMAGE_NAME:10play
            docker build -t $IMAGE_NAME:11 --build-arg ABIS=google_apis --build-arg ANDROID=android-30 .
            docker push $IMAGE_NAME:11
            docker build -t $IMAGE_NAME:11play --build-arg ABIS=google_apis_playstore --build-arg ANDROID=android-30 .
            docker push $IMAGE_NAME:11play
            docker build -t $IMAGE_NAME:12 --build-arg ABIS=google_apis --build-arg ANDROID=android-32 .
            docker push $IMAGE_NAME:12
            docker build -t $IMAGE_NAME:12play --build-arg ABIS=google_apis_playstore --build-arg ANDROID=android-32 .
            docker push $IMAGE_NAME:12play
            docker build -t $IMAGE_NAME:13 --build-arg ABIS=google_apis --build-arg ANDROID=android-33 .
            docker push $IMAGE_NAME:13
            docker build -t $IMAGE_NAME:13play --build-arg ABIS=google_apis_playstore --build-arg ANDROID=android-33 .
            docker push $IMAGE_NAME:13play
            docker build -t $IMAGE_NAME:latest --build-arg ABIS=google_apis_playstore --build-arg ANDROID=android-33 .
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - publish-latest:
          filters:
            branches:
              only: main
