version: 2
jobs:
  publish-latest:
    environment:
      IMAGE_NAME: miketruman/androiddocker
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker images
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t $IMAGE_NAME:71 --build-arg ABIS=google_apis --build-arg ANDROID=android-25 .
            docker push $IMAGE_NAME:71
            docker build -t $IMAGE_NAME:81 --build-arg ABIS=google_apis --build-arg ANDROID=android-27 .
            docker push $IMAGE_NAME:81
workflows:
  version: 2
  build-master:
    jobs:
      - publish-latest:
          filters:
            branches:
              only: main
